apiVersion: v2
name: sa-final-project
description: A Helm Chart for SA Project
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: mysql
    version: 9.4.1
    repository: https://charts.bitnami.com/bitnami
  - name: kafka
    version: 14.9.0
    repository: https://charts.bitnami.com/bitnami
  - name: mongodb
    repository: https://charts.bitnami.com/bitnami
    version: 13.1.7