service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/cors-allow-headers: Content-Type
    nginx.ingress.kubernetes.io/cors-allow-methods: "POST, GET, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://rent-now.s3-website.us-east-2.amazonaws.com"
    ingress.kubernetes.io/enable-cors: "true"

  hosts:
    - name: service
      paths:
        - path: /api/auth
          pathType: Prefix
          name: auth-svc-dev
          port: 80
        - path: /api/vehicles
          pathType: Prefix
          name: vehicle-svc-dev
          port: 80
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}



jwt:
  prefix: "6256B3E5CFC2C993"
  secret: "@@Tl8QnFYS2W&@KJkB9i3C*thwHX!mPW1J0NG2kZ5l6Sf6j7&!"
  issuer: edu.miu.cs590

mysql:
  auth:
    rootPassword: u32iuweuiuwekj
  username: root
  dbHost: mysql:3306


kafka:
  hostAddress: kafka
  zookeeper:
    enabled: true
  replicaCount: 3
  externalZookeeper: zookeeper

mongodb:
  auth:
    rootUser: root
    rootPassword: GnhsipoWHa1B29D5jFW^TTcU8gYtPg7^GSpmo
  dbHost: mongodb
  dbPort: 27017


app:
  activeProfile: prod


vehicle-svc:
  image:
    liveness:
      enabled: false
    readiness:
      enabled: false

services:
  vehicle: vehicle-svc
  auth: auth-svc
  booking: booking-svc
  email: email-svc
  review: review-svc
  payment: payment-svc