apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-jwt-secrets-{{ .Release.Revision }}
data:
  JWT_PREFIX: {{ .Values.jwt.prefix | b64enc }}
  JWT_SECRET: {{ .Values.jwt.secret | b64enc }}
  JWT_ISSUER: {{ .Values.jwt.issuer | b64enc }}