apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongo-secrets-{{ .Release.Revision }}
data:
  MONGODB_USERNAME: {{ .Values.mongodb.auth.rootUser | b64enc }}
  MONGODB_PASSWORD: {{ .Values.mongodb.auth.rootPassword | b64enc }}
