apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mongodb-config-{{ .Release.Revision }}
data:
  MONGODB_HOST: {{ .Release.Name }}-{{ .Values.mongodb.dbHost }}
  MONGODB_PORT: {{ .Values.mongodb.dbPort | quote }}
