apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mysql-config-{{ .Release.Revision }}
data:
  MYSQL_DB_HOST: {{ .Release.Name }}-{{ .Values.mysql.dbHost }}
  APP_PROFILE: {{ default "dev" .Values.app.activeProfile }}
