apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secrets-{{ .Release.Revision }}
data:
  MYSQL_PASSWORD: {{ .Values.mysql.auth.rootPassword | b64enc }}
  MYSQL_USER: {{ .Values.mysql.username | b64enc }}
