apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-maps-{{ .Release.Revision }}
data:
  MYSQL_DB_HOST: {{ .Release.Name }}-{{ .Values.mysql.dbHost }}
  SPRING_PROFILES_ACTIVE: {{ default "dev" .Values.app.activeProfile  }}
  MYSQL_DB_NAME: UserServiceDB
  APP_PROFILE: {{ default "dev" .Values.app.activeProfile }}



