apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "AuthSvc.fullname" . }}
  labels:
    {{- include "AuthSvc.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "AuthSvc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "AuthSvc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "AuthSvc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path:  {{ .Values.image.liveness.path }}
              port: {{ .Values.image.port }}
            initialDelaySeconds: {{ .Values.image.liveness.delay }}
            periodSeconds: {{ .Values.image.liveness.period }}
          readinessProbe:
            httpGet:
              path:  {{ .Values.image.readiness.path }}
              port: {{ .Values.image.port }}
            initialDelaySeconds: {{ .Values.image.readiness.delay }}
            periodSeconds: {{ .Values.image.readiness.period }}
          envFrom:
            {{- range .Values.secrets }}
            - secretRef:
                name: {{ $.Release.Name }}-{{ . }}-{{ $.Release.Revision }}
            {{- end }}
            {{- range .Values.configMaps }}
            - configMapRef:
                name: {{ $.Release.Name }}-{{ . }}-{{ $.Release.Revision }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
