# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build and Deploy to GKE

on:
  workflow_call:
    inputs:
      chart:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      chart:
        required: true
        type: string

env:
  DEPLOYMENT_NAME: usr-svc-dev # Add your deployment name here.

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      #      - run: |-
      #          gcloud --quiet auth configure-docker

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      # Build the Docker image
      #      - name: Build
      #        run: |-
      #          docker build \
      #            --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
      #            --build-arg GITHUB_SHA="$GITHUB_SHA" \
      #            --build-arg GITHUB_REF="$GITHUB_REF" \
      #            .
      #
      #      # Push the Docker image to Google Container Registry
      #      - name: Publish
      #        run: |-
      #          docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"

      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        working-directory: ./Projects
        run: |-
             helm upgrade dev . --install -f values.yaml
#      - name: Deploy
#        run: |-
#          kubectl apply -f https://raw.githubusercontent.com/rust42/SA-FinalProject-UserService/main/k8s/template.yaml
#          kubectl rollout status deployment/$DEPLOYMENT_NAME
#          kubectl get services -o wide